config/routes.rb
Rails.application.routes.draw do






  get 'search/result'

  devise_for :users

  # Page accessible for connected Users
  resources :users do
    # Depend on USer. Nested Resources
    resources :invoices
    resources :packagings
    resources :employees do
      member do
        get 'complete_profile'
      end

    end

  end

  resources :packages

  resources :legal_informations

  # Public Pages

  root "home#main"
  get 'contact', :to => "home#contact"



  get 'test/first'
  get 'test/second'
  get 'test/third'

end

app/views/layouts/administration_elements/_header_container.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2><%= yield(:main_title) %></h2>
        <ol class="breadcrumb">
        <%= yield(:breadcrumb) %>


        </ol>
    </div>
</div>

app/views/layouts/administration_elements/_navbar.html.erb
<div class="row border-bottom">
<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
<div class="navbar-header">

  <a class="navbar-minimalize minimalize-styl-2 btn btn-primary visible-xs" href="#"><i class="fa fa-bars"></i> </a>

  <%= form_tag({controller: "search", action: "result"}, method: "get", class: "navbar-form-custom") do %>

  <div class="form-group">
      <input type="text" placeholder="Recherche..." class="form-control" name="query" id="query">
  </div>

  <% end %>

</div>
    <ul class="nav navbar-top-links navbar-right">





        <li class="dropdown">
            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> Vous avez un nouveau message de l'équipe ALAN
                            <span class="pull-right text-muted small">Il y a 2 jours</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> Alain dupont a rempli son dossier. Il est assuré
                            <span class="pull-right text-muted small">Il y a 12 jours</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Paiement assurance ALAN effectué le 12/03/2016
                            <span class="pull-right text-muted small">Il y a 20 jours</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <div class="text-center link-block">
                        <a href="#">
                            <strong>Voir toutes les alertes</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </li>
            </ul>
        </li>

        <li>
              <%= link_to edit_user_path(current_user), class: "tooltip-tag", title: "Vos préférences" do %>
                <i class="fa fa-cogs"></i>
                <% end %>
        </li>


        <li>
            <%= link_to destroy_user_session_path, :method => :delete do %>
                <i class="fa fa-sign-out"></i> Déconnexion
            <% end %>
        </li>

    </ul>

</nav>
</div>

app/views/layouts/administration_elements/_sidebar.html.erb
<!-- Right Sidebar-->

<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <div class="dropdown profile-element">
          <div>
            <h2 class="text-center text-green">ALAN</h2>
            <img alt="image" class="img-circle hidden" src="img/profile_small.jpg"/>
          </div>
          <div class="text-center margin-bottom-10 text-12">
            <strong class="font-bold text-center text-white"><%= current_user.company_name || "Entreprise" %></strong>
          </div>

        </div>
        <div class="logo-element">
          AL
        </div>
      </li>
      <li class="active-link-container">
        <%= link_to current_user, class: "hidden-xs" do %>
        <div class="text-center padding-5">
          <i class="fa fa-th-large fa-2x"></i>
        </div>
        <div class="text-center padding-5">
          <h3>Accueil</h3>
        </div>
        <% end %>

        <%= link_to current_user, class: "visible-xs" do %>
          <i class="fa fa-th-large"></i>
          <span class="nav-label">Accueil</span>
        <% end %>
      </li>

      <li class="active-link-container">
        <%= link_to user_employees_path(current_user), class: "hidden-xs" do %>
        <div class="text-center padding-5">
          <i class="fa fa-users fa-2x"></i>
        </div>
        <div class="text-center padding-5">
          <h3>Assurés</h3>
        </div>
        <% end %>
        <%= link_to user_employees_path(current_user), class: "visible-xs" do %>
          <i class="fa fa-users"></i>
          <span class="nav-label">Assurés</span>
        <% end %>
      </li>

      <li class="active-link-container">

        <%= link_to packages_path, class: "hidden-xs" do %>
        <div class="text-center padding-5">
          <i class="fa fa-diamond fa-2x"></i>
        </div>
        <div class="text-center padding-5">
          <h3>Votre package</h3>
        </div>
        <% end %>
        <%= link_to packages_path, class: "visible-xs" do %>
          <i class="fa fa-diamond"></i>
          <span class="nav-label">Packages</span>

        <% end %>

      </li>

      <li class="active-link-container">

        <%= link_to user_invoices_path(current_user), class: "hidden-xs" do %>
        <div class="text-center padding-5">
          <i class="fa fa-money fa-2x"></i>
        </div>
        <div class="text-center padding-5">
          <h3>Facturation</h3>
        </div>
        <% end %>
        <%= link_to user_invoices_path(current_user), class: "visible-xs" do %>
          <i class="fa fa-money"></i>
          <span class="nav-label">Facturation</span>

        <% end %>

      </li>

      <li class="active-link-container">
        <%= link_to legal_informations_path, class: "hidden-xs" do %>
        <div class="text-center padding-5">
          <i class="fa fa-globe fa-2x"></i>
        </div>
        <div class="text-center padding-5">
          <h3>Portail légal</h3>
        </div>
        <% end %>
        <%= link_to legal_informations_path, class: "visible-xs" do %>
          <i class="fa fa-globe"></i>
          <span class="nav-label">Portail légal</span>

        <% end %>
      </li>

      






    </ul>

  </div>
</nav>


<%= content_for(:end_script) do %>
<script>

$(function() {
  var currentPage = location.pathname;
  $('.active-link-container').each(function() {
      var active = false;
      $(this).find("a").each( function() {
        var currentHref = $(this).attr('href');
        //alert($(this).attr('href'));
        if(currentHref == currentPage) {
            active = true;
        }
      })
      if (active == true){
        $(this).addClass("active");
      }
    })
});



</script>


<% end %>

<!-- End of Sidebar -->