config/routes.rb
Rails.application.routes.draw do






  get 'search/result'

  devise_for :users

  # Page accessible for connected Users
  resources :users do
    # Depend on USer. Nested Resources
    resources :invoices
    resources :packagings
    resources :employees do
      member do
        get 'complete_profile'
      end

    end

  end

  resources :packages

  resources :legal_informations

  # Public Pages

  root "home#main"
  get 'contact', :to => "home#contact"



  get 'test/first'
  get 'test/second'
  get 'test/third'

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id                   :integer          not null, primary key
#  first_name           :string
#  last_name            :string
#  user_id              :integer
#  birthday_date        :date
#  health_comment       :text
#  admin_status         :integer
#  complete_information :boolean          default(FALSE)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  research_name        :string
#  email                :string
#  access_token         :string
#

class Employee < ActiveRecord::Base


  ##-- Validations -----------------
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "only allows letters" } # Validation of email format
  validates :user_id, presence: true

  ##-- Callbacks -------------------
  before_validation :sanitize_email
  before_validation :update_research_name, if: :name_changed?

  after_create :generate_access_token
  after_create :send_complete_information_email


  ##-- Associations ----------------
  belongs_to :user # Employee belongs to company that are represented by User here. I agree not a good name for company = User ;)

  ##-- Methods ----------------

  # Beautify URLS
  def to_param
  "#{id} #{full_name}".parameterize
  end

  # Method for searching and pagination through a collection of employee (must be in the model)
  def self.search_and_paginate(params)
    self.general_search(params).paginate(:page => params[:page], :per_page => 30)
  end

  # General search and ordering for the class
  def self.general_search(attributes)
    attributes.inject(self) do |scope, (key, value)|
      #return scope.scoped if value.blank?
      if value.blank?
        scope.all
      else
          case key.to_sym
          when :name
           name = I18n.transliterate(value.to_s.downcase.strip).to_s # Just remove the accents and normalize
           scope.where('employees.research_name ILIKE ? OR employees.email ILIKE ?',  "%#{name}%", "%#{name}%", "%#{name}%")

          when :order # order=field-(ASC|DESC)
            attribute, order = value.split("-")
            if self.column_names.include? attribute.to_s
              scope.order("#{self.table_name}.#{attribute} #{order}")
            else
              scope
            end
          else # unknown key (do nothing or raise error, as you prefer to)
          scope.all
          end

      end
    end
  end

  # Full_name method to display the first_name followed by the last_name
  def full_name
    return (first_name.to_s + ' ' + last_name.to_s).strip
  end

  # Method to simualate a Date of subscription. Just For présentation
  #TODO: Remove when progress
  def subscription_date
    return Date.today - 10.day
  end

  # Guess the email of the employee
  def guess_email
    company_domain = self.user.company_domain
    if company_domain
      email = self.first_name.to_s.downcase + "." + self.last_name.to_s.downcase + "@" + company_domain.to_s
      return email
    else
      "Impossible de deviner l'adresse mail, le domaine de l'entreprise n'est pas défini"
    end
  end

  # Method that change the status of the employee
  def has_completed_information
    self.update(:complete_information => true)
  end

  def correct_access_token(params)
    true
  end

  # Send the email to the employee to complete his profile
  def send_complete_information_email
    EmployeeMailer.complete_profile(self).deliver
  end

  private

  # Sanitize the email in the model.
  def sanitize_email
    if !self.email.blank?
      self.email = I18n.transliterate(self.email.to_s.downcase.strip.gsub(' ', '-'))
    end
  end

  # Generate access token to access the page for the Employee. Future development
  def generate_access_token
    if self.access_token.blank?
     self.update_column(:access_token, SecureRandom.urlsafe_base64(nil, false))
    end
  end

  # Update the field used for researching through employee. NOt the best technique I agree but the fastest to have decent results without paying on Heroku
  def update_research_name
    self.research_name = I18n.transliterate(self.full_name.to_s.downcase.strip).to_s
  end

  # Method to know when the research_name must be updated
  def name_changed?
    first_name_changed? || last_name_changed?
  end


end

app/controllers/employees_controller.rb
# == Schema Information
#
# Table name: employees
#
#  id                   :integer          not null, primary key
#  first_name           :string
#  last_name            :string
#  user_id              :integer
#  birthday_date        :date
#  health_comment       :text
#  admin_status         :integer
#  complete_information :boolean          default(FALSE)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  research_name        :string
#  email                :string
#  access_token         :string
#

class EmployeesController < ApplicationController
  before_action :authenticate_user, except: [:complete_profile]
  before_action :set_current_user, except: [:complete_profile]

  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  layout 'administration'

  # GET /employees
  def index
    @employees = @user.employees.search_and_paginate(params)
  end

  # GET /employees/1
  def show

  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  def create
    @employee = @user.employees.build(employee_params)

    if @employee.save
      redirect_to user_employee_path(@user, @employee), notice: 'Votre nouvel assuré a été enregistré avec succès. Un email sera envoyé pour compléter son profil'
    else
      render :new
    end
  end

  # PATCH/PUT /employees/1
  def update
    if @employee.update(employee_params)
      redirect_to user_employee_path(current_user, @employee), notice: "Les informations de base sur l'assuré ont été mises à jour"
    else
      render :edit
    end
  end

  # DELETE /employees/1
  def destroy
    @employee.destroy
    redirect_to user_employees_path(current_user), notice: 'Employé supprimé de vos assurés'
  end

  # New route to send a new email of inscription for the employee. Respond in JS
  def send_new_inscription_email
    @employee.send_complete_information_email
    respond_to do |format|
      format.js
    end
  end

  # Route for the complete profile function
  def complete_profile
    @user = User.find_by(id: params[:user_id])
    @employee = Employee.find_by(id: params[:id])

    if (!@user.nil?) & (!@employee.nil?)
      if @employee.correct_access_token(params)
        @employee.has_completed_information
      else
        redirect_to root_path, notice: "Impossible d'accèder à la page"
      end
    else
      redirect_to root_path, notice: "Impossible d'accèder à la page"
    end
    render :layout => 'application'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def set_user
      if current_user
        @user = current_user
      else
        redirect_to root_path, notice: "Vous devez être connecté afin de consulter cette page"
      end
    end

    # Only allow a trusted parameter "white list" through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :user_id, :birthday_date, :health_comment, :admin_status, :complete_information, :email)
    end
end

app/helpers/employees_helper.rb
# == Schema Information
#
# Table name: employees
#
#  id                   :integer          not null, primary key
#  first_name           :string
#  last_name            :string
#  user_id              :integer
#  birthday_date        :date
#  health_comment       :text
#  admin_status         :integer
#  complete_information :boolean          default(FALSE)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  research_name        :string
#  email                :string
#  access_token         :string
#

module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div class="forum-item active">
  <div class="row">
    <div class="col-md-9">
      <div class="forum-icon">
        <i class="fa fa-user"></i>
      </div>
      <%= link_to employee.full_name, user_employee_path(user, employee), class: "forum-item-title" %>

      <div class="forum-sub-title">Assuré depuis le :
        <%= l employee.subscription_date %></div>
    </div>
    <div class="col-md-1 forum-info">
      <span class="views-number">
        28
      </span>
      <div>
        <small>ans</small>
      </div>
    </div>
    <div class="col-md-2 forum-info">

      <% if employee.complete_information %>
      <span class="">
        <i class="fa fa-check fa-2x text-green"></i>
      </span>
      <div>
        <small>Dossier complet</small>
      </div>
      <% else %>
      <span class="">
        <i class="fa fa-times fa-2x text-danger"></i>
      </span>
      <div>
        <small>Dossier incomplet</small>
      </div>

      <% end %>
    </div>

  </div>
</div>

app/views/employees/_employees_list.html.erb
<% if !employees.empty? %>

<div class="text-center">
	<%= will_paginate employees, renderer: BootstrapPagination::Rails  %>
</div>

<div class="ibox-content forum-container">

  <%= render partial: "employees/employee", collection: employees, as: :employee, locals: {user: user} %>

</div>

<div class="text-center">
	<%= will_paginate employees, renderer: BootstrapPagination::Rails  %>
</div>

<% else %>

<div class="ibox-content ">

  <div class="p-xs">

    <h3>Vous n'avez pas encore assuré d'employé sur Alan. Rien de plus simple il vous suffit de nous donner son prénom et son nom et nous allons deviner son adresse mail et lui envoyer un mail afin qu'il complète son profil</h3>

  </div>

  <div class="text-center">
    <%= link_to new_user_employee_path(user),class: "btn btn-primary text-uppercase" do %>
    <i class="fa fa-user"></i>
    Ajouter un nouvel Employé
    <% end %>
  </div>

</div>
<% end %>

app/views/employees/_form.html.erb
<%= form_for([@user, @employee],  html: {class: "form-horizontal"}) do |f| %>
  <% if @employee.errors.any? %>



    <div id="error_explanation" >
      <h2><%= pluralize(@employee.errors.count, "erreur") %> dans le formulaire :</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>



  <div class="form-group">
    <%= f.label :first_name, "Prénom", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, class: "form-control", placeholder: "Alain", required: true %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :last_name, "Nom", class: "col-sm-2 control-label"  %>
        <div class="col-sm-10">
    <%= f.text_field :last_name, class: "form-control", placeholder: "Dupont" , required: true %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <%= f.label :email, "Email", class: "col-sm-2 control-label"  %>
        <div class="col-sm-10">
    <%= f.email_field :email, class: "form-control guess-email", placeholder: "alain.dupont@yourcompany.fr", required: true %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>
  <div class="form-group text-center">
    <%= f.submit "Assurer", class: "btn btn-primary btn-lg text-uppercase" %>
  </div>
<% end %>


<%= content_for(:end_script) do %>
<script>

function update_email_field(){
  var first_name = $('#employee_first_name').val();
  var last_name = $('#employee_last_name').val();
  var domain = "<%= @user.company_domain.to_s %>";
  var email = first_name + '.' + last_name + '@' + domain;
  $('#employee_email').val(email.latinize().replace(/ /g,"-"));


}
$(function() {
  $('#employee_first_name').on( "change",function() {
    update_email_field();
  })
  $('#employee_last_name').on( "change",function() {
    update_email_field();
  })

})
</script>

<% end %>

app/views/employees/complete_profile.html.erb
<section class="back-image-landing back-green full-height margin-top-20">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3 col-sm-offset-3 padding-20 background-opacity margin-top-100 text-white ">
        <h1 class=" text-center"><%= @employee.full_name %></h1>
        <div class="margin-top-20">
          <h1 class="text-center text-uppercase">VOUS ÊTES Désormais inscrit SUR ALAN</h1>
          <div class="text-center">
            Votre dossier est désormais complet
          </div>
        </div>
        <div class="text-center margin-top-20" >
          <i class="fa fa-check fa-2x"></i>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/employees/edit.html.erb
<%= provide(:main_title, "Modification du dossier employé" ) %>
<%= content_for(:breadcrumb) do %>
<li>
    <%= link_to "Accueil", current_user %>
</li>
<li>
  <%= link_to "Employés assurés", user_employees_path(current_user) %>
</li>

<li>
  <%= link_to "Employés assurés", user_employee_path(current_user, @employee) %>
</li>
<li class="active">
    <strong>Modifier informations générales</strong>
</li>
<% end %>



<div class="row">

    <div class="col-md-12">
<div class="wrapper wrapper-content animated fadeInRight">
      <div class="ibox-content m-b-sm border-bottom">


          <div class="p-xs">
              <div class="pull-left m-r-md">
                  <i class="fa fa-users text-navy mid-icon"></i>
              </div>
              <h2>Modification des données de l'assuré</h2>
              <span>Modifier les informations sur votre employé.</span>
          </div>


      </div>




      </div>
    </div>
  </div>


  <div class="row">

      <div class="col-md-6 col-md-offset-3">

          <div class="ibox-content ">
            <h2 class="m-lg text-center">Un email sera envoyé à votre employé pour compléter son profil.</h2>


          <%= render "form" %>

        </div>

      </div>
    </div>

app/views/employees/index.html.erb
<%= provide(:main_title, "Gestion des assurés" ) %>
<%= content_for(:breadcrumb) do %>
<li>
<a href="index.html">Accueil</a>
</li>
<li class="active">
<strong>Employés assurés</strong>
</li>
<% end %>

<div class="row">

<div class="col-md-12">
  <div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox-content m-b-sm border-bottom">

      <div class="pull-right">
        <%= link_to "Ajouter un nouvel Employé", new_user_employee_path(@user),class: "btn btn-primary btn-lg" %>
      </div>

      <div class="p-xs">
        <div class="pull-left m-r-md">
          <i class="fa fa-users text-navy mid-icon"></i>
        </div>
        <h2>
          <% if @employees.count > 1 %>
          <%= @employees.count %>
          Employés assurés

        <% else %>
          <%= @employees.count %>
          Employé assuré

          <% end %>

        </h2>
        <span>Vous pouvez suivre ici le statut de chacun de vos employés et gérer l'assurance pour vos employés</span>
      </div>

    </div>

    <%= render partial: "employees/employees_list", locals: {employees: @employees, user: @user} %>

  </div>
</div>
</div>

app/views/employees/new.html.erb
<%= provide(:main_title, "Ajout d'un nouvel employé" ) %>
<%= content_for(:breadcrumb) do %>
<li>
    <%= link_to "Accueil", current_user %>
</li>
<li>
  <%= link_to "Employés assurés", user_employees_path %>
</li>
<li class="active">
    <strong>Nouvel employé</strong>
</li>
<% end %>



<div class="row">

    <div class="col-md-12">
<div class="wrapper wrapper-content animated fadeInRight">
      <div class="ibox-content m-b-sm border-bottom">


          <div class="p-xs">
              <div class="pull-left m-r-md">
                  <i class="fa fa-users text-navy mid-icon"></i>
              </div>
              <h2>Ajout d'un nouvel assuré</h2>
              <span>Vous pouvez ajouter très facilement un nouvel employé à la liste de vos assurés. Alan se charge du reste !</span>
          </div>


      </div>




      </div>
    </div>
  </div>


  <div class="row">

      <div class="col-md-6 col-md-offset-3">

          <div class="ibox-content ">
            <h2 class="m-lg text-center">Un email sera envoyé à votre employé pour compléter son profil</h2>


          <%= render "form" %>

        </div>

      </div>
    </div>

app/views/employees/show.html.erb
<%= provide(:main_title, @employee.full_name ) %>
<%= content_for(:breadcrumb) do %>
<li>
<%= link_to "Accueil", current_user %>
</li>
<li>
<%= link_to "Employés assurés", user_employees_path %>
</li>
<li class="active">
<strong><%= @employee.full_name %></strong>
</li>
<% end %>

<div class="row">
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="col-md-4">
    <div class="widget lazur-bg no-padding">
      <div class="p-m">
        <h1 class="m-xs text-center">Assuré par le Plan A à 50 %</h1>



      </div>

    </div>
  </div>
  <div class="col-md-4">
    <div class="widget lazur-bg no-padding">
      <div class="p-m">
        <h1 class="m-xs text-center">Coût employé : 10 € / mois</h1>


      </div>

    </div>
  </div>
  <div class="col-md-4">
    <div class="widget lazur-bg no-padding">
      <div class="p-m">
        <h1 class="m-xs text-center">Coût employeur : 15 € / mois</h1>



      </div>

    </div>
  </div>
</div>
</div>

<div class="row">
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="col-md-12">
    <div class="ibox-content m-b-sm border-bottom">

      <% if @employee.complete_information %>

      <div class="pull-right">

        <%= link_to "Modifier les informations", edit_user_employee_path(@user, @employee),class: "btn btn-primary" %>
      </div>

      <div class="p-xs">
        <div class="pull-left m-r-md">
          <i class="fa fa-check text-green mid-icon"></i>
        </div>
        <h2>
          Statut : Dossier complet

        </h2>
        <span>L'assuré est désormais assuré.</span>
      </div>

      <% else %>

      <div class="pull-right">
        <%= link_to "Envoyer un nouvel email", "#",class: "btn btn-primary" %>
        <%= link_to "Modifier les informations", edit_user_employee_path(@user, @employee),class: "btn btn-primary" %>
      </div>

      <div class="p-xs">
        <div class="pull-left m-r-md">
          <i class="fa fa-times text-danger mid-icon"></i>
        </div>
        <h2>
          Statut : Dossier incomplet

        </h2>
        <span>L'assuré n'a pas encore rempli le dossier afin de valider son compte et être assuré.</span>
      </div>

      <% end %>

    </div>

  </div>
</div>
</div>

<div class="row">
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="col-md-12">

    <div class="ibox">
      <div class="ibox-content">
        <div class="row">
          <div class="col-lg-12">
            <h2 class="page-header">Informations générales</h2>

            <div>
              <h3>Prénom :
                <%= @employee.first_name %></h3>
            </div>
            <div>
              <h3>Nom :
                <%= @employee.last_name %></h3>
            </div>

            <div>
              <h3>Email Entreprise :
                <%= @employee.email || @employee.guess_email %></h3>
            </div>
            <div>
              <h3>Date de souscription :
                <%= l @employee.subscription_date %></h3>
            </div>
            <div>
              <h3>Assuré depuis le :
                <%= l @employee.subscription_date %></h3>
            </div>

          </div>
        </div>

        <div class="row m-t-sm">
          <div class="col-lg-12">

            <h2 class="page-header">
              Options choisies
              <small>(peut être à ne pas afficher pour l'employeur mais ca peut etre assurance conjoint par exemple, prévoyance etc..)</small>
            </h2>
            <div class="panel blank-panel">

              <div class="tab-pane" id="tab-2">

                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>Choix</th>
                      <th>Nom de l'option</th>
                      <th>Date de début</th>

                      <th>Détails</th>
                      <th>Tarifs</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                        <span class="label label-primary">
                          <i class="fa fa-check"></i>
                        </span>
                      </td>
                      <td>
                        Options 1
                      </td>
                      <td>
                        12/04/2016
                      </td>

                      <td>
                        <p class="small">
                          L'option dentaire permet de se faire rembourser les frais dentaires .......
                        </p>
                      </td>
                      <td>
                        10 €
                      </td>

                    </tr>

                    <tr>
                      <td>
                        <span class="label label-primary">
                          <i class="fa fa-check"></i>
                        </span>
                      </td>
                      <td>
                        Options 2
                      </td>
                      <td>
                        12/04/2016
                      </td>

                      <td>
                        <p class="small">
                          L'option dentaire permet de se faire rembourser les frais dentaires .......
                        </p>
                      </td>

                      <td>
                        10 €
                      </td>

                    </tr>
                    <tr>
                      <td>
                        <span class="label label-primary">
                          <i class="fa fa-check"></i>
                        </span>
                      </td>
                      <td>
                        Options 3
                      </td>
                      <td>
                        12/04/2016
                      </td>

                      <td>
                        <p class="small">
                          L'option dentaire permet de se faire rembourser les frais dentaires .......
                        </p>
                      </td>

                      <td>
                        10 €
                      </td>

                    </tr>
                    <tr>
                      <td>
                        <span class="label label-primary">
                          <i class="fa fa-check"></i>
                        </span>
                      </td>
                      <td>
                        Options 4
                      </td>
                      <td>
                        12/04/2016
                      </td>

                      <td>
                        <p class="small">
                          L'option dentaire permet de se faire rembourser les frais dentaires .......
                        </p>
                      </td>

                      <td>
                        10 €
                      </td>

                    </tr>
                    <tr>
                      <td>
                        <span class="label label-primary">
                          <i class="fa fa-check"></i>
                        </span>
                      </td>
                      <td>
                        Options 5
                      </td>
                      <td>
                        12/04/2016
                      </td>

                      <td>
                        <p class="small">
                          L'option dentaire permet de se faire rembourser les frais dentaires .......
                        </p>
                      </td>

                      <td>
                        10 €
                      </td>

                    </tr>
                    <tr>
                      <td>
                        <span class="label label-primary">
                          <i class="fa fa-check"></i>
                        </span>
                      </td>
                      <td>
                        Options 6
                      </td>
                      <td>
                        12/04/2016
                      </td>

                      <td>
                        <p class="small">
                          L'option dentaire permet de se faire rembourser les frais dentaires .......
                        </p>
                      </td>

                      <td>
                        15 €
                      </td>

                    </tr>
                    <tr>
                      <td>
                        <span class="label label-primary">
                          <i class="fa fa-check"></i>
                        </span>
                      </td>
                      <td>
                        Options 7
                      </td>
                      <td>
                        12/04/2016
                      </td>

                      <td>
                        <p class="small">
                          L'option dentaire permet de se faire rembourser les frais dentaires .......
                        </p>
                      </td>
                      <td>
                        30 €
                      </td>

                    </tr>

                  </tbody>
                </table>

              </div>
            </div>

          </div>

        </div>

        <div class="row m-t-sm">
          <div class="col-lg-12">

            <h2 class="">
              Notifications du compte
              <small>(valeur d'exemple, système de notification non codé)</small>
            </h2>

            <div class="ibox-content ">

              <%= render partial: "notifications/notification", locals:{ title: "Dossier Rempli", description: "Les accords de branche etc...", date: "26/02/2016 15h37", active: "active", type: "fa-user" } %>

              <%= render partial: "notifications/notification", locals:{ title: "Employé inscrit, dossier à completer envoyé", description: "Un dossier a été envoyé afin que votre employé remplisse les derniers éléments nécessaires à l'assurance", date:
              "23/02/2016 16h00", active: "", type: "fa-user" } %>

            </div>

          </div>
        </div>

        <div class="row m-t-sm">
          <div class="col-lg-12">

            <h2 class="page-header">
              Suppression du compte</h2>

            <div class="alert alert-info">
              Si vous souhaitez supprimer un employé de la liste de vos assurés, vous pouvez le faire depuis votre esapge de gestion Alan. N'oubliez pas vos obligations légales à ce sujet. Consultez
              <a href="#">notre article</a>
              pour en savoir plus.
            </div>

            <div class=" padding-5">
              <%= link_to "Supprimer cet employé des assurés", user_employee_path(@user, @employee), method: :delete, data: { confirm: 'Etes vous sur ?' }, class: "btn btn-danger" %>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>