config/routes.rb
Rails.application.routes.draw do






  get 'search/result'

  devise_for :users

  # Page accessible for connected Users
  resources :users do
    # Depend on USer. Nested Resources
    resources :invoices
    resources :packagings
    resources :employees do
      member do
        get 'complete_profile'
      end

    end

  end

  resources :packages

  resources :legal_informations

  # Public Pages

  root "home#main"
  get 'contact', :to => "home#contact"



  get 'test/first'
  get 'test/second'
  get 'test/third'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  first_name             :string
#  last_name              :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  company_name           :string
#  company_domain         :string
#  company_address        :string
#  company_phone          :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ##-- Validations -----------------
  validates :first_name, presence: true
  validates :last_name, presence: true

  ##-- Callbacks -------------------
  before_validation :guess_company_domain, if: :company_name_changed?

  ##-- Associations ----------------

  has_many :employees, dependent: :destroy
  has_many :invoices, dependent: :destroy
  has_one :packaging, dependent: :destroy


  ##-- Methods----------------


  # Beautify URLS
  def to_param
  "#{id} #{full_name}".parameterize
  end

  # Basic methods with name
  def full_name
    first_name.to_s + ' ' + last_name.to_s
  end

  # Method that will guess the company domain from the company name.
  def guess_company_domain
    if self.company_domain.blank?
      string = self.company_name.to_s.downcase.gsub(' ', '') + ".fr"
      self.company_domain = string
    end
  end
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  first_name             :string
#  last_name              :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  company_name           :string
#  company_domain         :string
#  company_address        :string
#  company_phone          :string
#

class UsersController < ApplicationController
  before_action :authenticate_user
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout 'administration'

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @employees_count = @user.employees.count
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Set the user variable and check that it is the same than the current_user.
    def set_user
      user = User.find_by(id: params[:id])
      if (user.nil?) || (user != current_user)
        redirect_to root_path, notice: "Vous n'êtes pas autorisé à accéder à cette page"
        return
      end
      @user = user
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :refund_percent, :company_name, :company_domain, :company_phone, :company_address)
    end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">

      <div class="ibox-content">

        <h2 class="page-header">Informations générales</h2>
        <%= form_for(@user,  html: {class: "form-horizontal"}) do |f| %>
        <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %>
            prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="form-group">
          <%= f.label :first_name, "Prénom", class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <%= f.label :last_name, "Nom", class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <%= f.label :company_name, "Nom de l'entreprise", class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :company_name, class: "form-control" %>
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <%= f.label :company_domain, "Domaine de l'entreprise", class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :company_domain, class: "form-control" %>
          </div>
        </div>
        <div class="hr-line-dashed"></div>

        <div class="actions text-center">
          <%= f.submit "Mettre à jour", class: "btn btn-primary btn-lg" %>
        </div>

        <% end %>

    </div>
  </div>
</div>
</div>

app/views/users/edit.html.erb
<%= provide(:main_title, "Préférences de votre compte" ) %>
<%= content_for(:breadcrumb) do %>
<li>
<%= link_to "Accueil", current_user %>
</li>

<li class="active">
<strong>Préférences de votre compte</strong>
</li>
<% end %>


<div class="row">
  <div class="col-md-12">
  <div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox-content m-b-sm border-bottom">




        <div class="p-xs">
            <div class="pull-left m-r-md">
                <i class="fa fa-cogs text-navy mid-icon"></i>
            </div>
            <h2>Modifier toutes les informations de votre compte Entreprise</h2>
            <span>Toutes les modifications relatives à votre compte entreprise se font ici (à l'exception du choix du package assurance)</span>
        </div>


    </div>
    <%= render 'form' %>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <div class="ibox-content">
                  <h2 class="page-header">Préférences notifications</h2>
                    <form method="get" class="form-horizontal">


                        <div class="form-group"><label class="col-sm-2 control-label">Envois Emails <br/>
                            <small class="text-navy">Les emails pour vous notifier des activités sur Alan</small></label>

                            <div class="col-sm-10">
                                <div><label> <input type="checkbox" value=""> Option 1 </label></div>
                                <div><label> <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"> Option 2
                                     </label></div>
                                <div><label> <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> Option 2 bis
                                   </label></div>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group"><label class="col-sm-2 control-label">Envois SMS</label>

                            <div class="col-sm-10">

                                <div class="i-checks"><label> <input type="radio" value="option1" name="a"> <i></i> Option 1 </label></div>
                                <div class="i-checks"><label> <input type="radio" checked="" value="option2" name="a"> <i></i> Option 2</label></div>

                            </div>
                        </div>





                        <div class="hr-line-dashed"></div>
                        <div class="form-group text-center">


                                <button class="btn btn-primary btn-lg text-center" type="submit">Sauvegarder</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <div class="ibox-content">

                  <%= link_to "Modifier vos identifiants", edit_user_registration_path, class: "btn btn-primary btn-lg" %>

                </div>

              </div>
            </div>
          </div>

  </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>User</th>
      <th>Birthday date</th>
      <th>Health comment</th>
      <th>Admin status</th>
      <th>Complete information</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.user %></td>
        <td><%= user.birthday_date %></td>
        <td><%= user.health_comment %></td>
        <td><%= user.admin_status %></td>
        <td><%= user.complete_information %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_user_path %>

app/views/users/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= provide(:main_title, "Accueil" ) %>
<%= content_for(:breadcrumb) do %>

<li class="active">
<strong>Résumé de votre compte ALAN</strong>
</li>
<% end %>

<div class="row">
  <div class="wrapper wrapper-content animated fadeInRight">
<div class="col-md-4">
  <div class="widget lazur-bg no-padding">
    <div class="p-m">
      <h1 class="m-xs text-center">Vous suivez le plan A</h1>

      <h3 class="font-bold text-center ">
        50 % de remboursement
      </h3>
      <h3 class="text-center">
        <%= link_to "Voir mon plan", packages_path, class: "btn btn-primary text-uppercase" %></h3>
    </div>

  </div>
</div>
<div class="col-md-4">
  <div class="widget lazur-bg no-padding">
    <div class="p-m">
      <h1 class="m-xs text-center">
        <% if @employees_count != 1 %>
          <%= @employees_count %> employés assurés
        <% else %>
          <%= @employees_count %> employé assuré
        <% end %>

      </h1>
      <h3 class="font-bold text-center ">
        3 notifications importantes
      </h3>
      <h3 class="text-center">
        <%= link_to "Gestion des assurés", user_employees_path(@user), class: "btn btn-primary text-uppercase" %></h3>
    </div>

  </div>
</div>
<div class="col-md-4">
  <div class="widget lazur-bg no-padding">
    <div class="p-m">
      <h1 class="m-xs text-center">Coût : 420 € / mois</h1>

      <h3 class="font-bold text-center ">
        Prochain prélevement : 11/04/2016
      </h3>
      <h3 class="text-center">
        <%= link_to "Suivi des paiements", user_invoices_path(current_user), class: "btn btn-primary text-uppercase" %></h3>
    </div>

  </div>
</div>
</div>
</div>

<div class="row">
<div class="col-md-6">
  <div class="wrapper wrapper-content animated fadeInRight">

    <div class="ibox-content m-b-sm border-bottom">
      <div class="p-xs">
        <div class="pull-left m-r-md">
          <i class="fa fa-bell text-navy mid-icon"></i>
        </div>
        <h2>Notifications de votre compte</h2>
        <span>Les dernières alertes et notifications de votre compte Alan Assurance.</span>
      </div>
    </div>

    <div class="ibox-content forum-container">



      <%= render partial: "notifications/notification", locals:{ title: "Nouveau paiement effectué", description: "Un nouveau paiement a été effectué par ALAN, la facture est disponible dans l'espace paiements", date: "01/04/2016", active: "active", type: "fa-money" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Nouvel Employé assuré : Alain Dupont a complété son dossier", description: "Alain dupont a complété son dossier. Il est désormais assuré par Alan", date: "15/03/2016", active: "", type: "fa-user" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Nouvelle fonctionnalité sur Alan", description: "Ajouter un employé en deux clics !", date: "15/03/2016", active: "", type: "fa-edit" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Création d'un nouvel employé : Alain Dupont", description: "Vous avez inscrit un nouvel employé (Alain Dupont). Un email lui a été envoyé afin qu'il complète son dossier", date: "15/03/2016", active: "", type: "fa-user" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Nouveau paiement effectué", description: "Un nouveau paiement a été effectué par ALAN, la facture est disponible dans l'espace paiements", date: "01/04/2016", active: "", type: "fa-money" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Nouvel Employé assuré : Alain Dupont a complété son dossier", description: "Alain dupont a complété son dossier. Il est désormais assuré par Alan", date: "15/03/2016", active: "", type: "fa-user" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Nouvelle fonctionnalité sur Alan", description: "Ajouter un employé en deux clics !", date: "15/03/2016", active: "", type: "fa-edit" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Création d'un nouvel employé : Alain Dupont", description: "Vous avez inscrit un nouvel employé (Alain Dupont). Un email lui a été envoyé afin qu'il complète son dossier", date: "15/03/2016", active: "", type: "fa-user" } %>

      <div class="text-center padding-5">
      <%=  link_to "Voir toutes les notifications", "#", class: "btn btn-primary text-center" %>
      </div>



    </div>
  </div>
</div>

<div class="col-md-6">
  <div class="wrapper wrapper-content animated fadeInRight">

    <div class="ibox-content m-b-sm border-bottom">
      <div class="p-xs">
        <div class="pull-left m-r-md">
          <i class="fa fa-globe text-navy mid-icon"></i>
        </div>
        <h2>Nouvelles du portail légal</h2>
        <span>Toutes les informations légales sur vos obligations en tant qu'employeur.</span>
      </div>
    </div>

    <div class="ibox-content forum-container">

      <%= render partial: "notifications/notification", locals:{ title: "Vos obligations légales, Mise à jour", description: "Les accords de branche etc...", date: "26/09/2015", active: "active", type: "fa-shield" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Vous n'êtes plus obligés d'enregistrer vos employés....", description: "Nouvelles Flash sur la santé ou la legislation", date: "26/09/2015", active: "", type: "fa-bolt" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Evénement de ALAN Assurance", description: "Journée Alan réservez votre journée", date: "26/08/2015", active: "", type: "fa-calendar" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Obligation d'assurer tous vos salariés", description: "La nouvelle loi prévoit.....", date: "26/08/2015", active: "", type: "fa-bomb" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Vos obligations légales, Mise à jour", description: "Les accords de branche etc...", date: "26/09/2015", active: "", type: "fa-shield" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Vous n'êtes plus obligés d'enregistrer vos employés....", description: "Nouvelles Flash sur la santé ou la legislation", date: "26/09/2015", active: "", type: "fa-bolt" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Evénement de ALAN Assurance", description: "Journée Alan réservez votre journée", date: "26/08/2015", active: "", type: "fa-calendar" } %>

      <%= render partial: "notifications/notification", locals:{ title: "Obligation d'assurer tous vos salariés", description: "La nouvelle loi prévoit.....", date: "26/08/2015", active: "", type: "fa-bomb" } %>

      <div class="text-center padding-5">
      <%=  link_to "Voir toutes les nouvelles", "#", class: "btn btn-primary text-center" %>
      </div>

    </div>
  </div>
</div>
</div>