config/routes.rb
Rails.application.routes.draw do






  get 'search/result'

  devise_for :users

  # Page accessible for connected Users
  resources :users do
    # Depend on USer. Nested Resources
    resources :invoices
    resources :packagings
    resources :employees do
      member do
        get 'complete_profile'
      end

    end

  end

  resources :packages

  resources :legal_informations

  # Public Pages

  root "home#main"
  get 'contact', :to => "home#contact"



  get 'test/first'
  get 'test/second'
  get 'test/third'

end

app/models/packaging.rb
# == Schema Information
#
# Table name: packagings
#
#  id             :integer          not null, primary key
#  package_id     :integer
#  user_id        :integer
#  refund_percent :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Packaging < ActiveRecord::Base


  ##-- Validations -----------------
  validates :package_id, presence: true
  validates :user_id, presence: true
  validates :refund_percent, presence: true
  

  ##-- Callbacks -------------------


  ##-- Associations ----------------
  belongs_to :package
  belongs_to :user


  ##-- Methods----------------
end

app/controllers/packagings_controller.rb
# == Schema Information
#
# Table name: packagings
#
#  id             :integer          not null, primary key
#  package_id     :integer
#  user_id        :integer
#  refund_percent :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class PackagingsController < ApplicationController
  before_action :authenticate_user
  before_action :set_current_user

  before_action :set_packaging, only: [:show, :edit, :update, :destroy]
  layout 'administration'

  # GET /packagings
  def index
    @packagings = Packaging.all
  end

  # GET /packagings/1
  def show
  end

  # GET /packagings/new
  def new
    @packaging = Packaging.new
  end

  # GET /packagings/1/edit
  def edit
  end

  # POST /packagings
  def create
    @packaging = Packaging.new(packaging_params)

    if @packaging.save
      redirect_to @packaging, notice: 'Packaging was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /packagings/1
  def update
    if @packaging.update(packaging_params)
      redirect_to @packaging, notice: 'Packaging was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /packagings/1
  def destroy
    @packaging.destroy
    redirect_to packagings_url, notice: 'Packaging was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_packaging
      @packaging = Packaging.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def packaging_params
      params.require(:packaging).permit(:package_id, :user_id, :refund_percent)
    end
end

app/helpers/packagings_helper.rb
# == Schema Information
#
# Table name: packagings
#
#  id             :integer          not null, primary key
#  package_id     :integer
#  user_id        :integer
#  refund_percent :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

module PackagingsHelper
end

app/views/packagings/_form.html.erb
<%= form_for(@packaging) do |f| %>
  <% if @packaging.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@packaging.errors.count, "error") %> prohibited this packaging from being saved:</h2>

      <ul>
      <% @packaging.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :package_id %><br>
    <%= f.text_field :package_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :refund_percent %><br>
    <%= f.text_field :refund_percent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/packagings/edit.html.erb
<h1>Editing Packaging</h1>

<%= render 'form' %>

<%= link_to 'Show', @packaging %> |
<%= link_to 'Back', packagings_path %>

app/views/packagings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Packagings</h1>

<table>
  <thead>
    <tr>
      <th>Package</th>
      <th>User</th>
      <th>Refund percent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @packagings.each do |packaging| %>
      <tr>
        <td><%= packaging.package %></td>
        <td><%= packaging.user %></td>
        <td><%= packaging.refund_percent %></td>
        <td><%= link_to 'Show', packaging %></td>
        <td><%= link_to 'Edit', edit_packaging_path(packaging) %></td>
        <td><%= link_to 'Destroy', packaging, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Packaging', new_packaging_path %>

app/views/packagings/new.html.erb
<h1>New Packaging</h1>

<%= render 'form' %>

<%= link_to 'Back', packagings_path %>

app/views/packagings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Package:</strong>
  <%= @packaging.package %>
</p>

<p>
  <strong>User:</strong>
  <%= @packaging.user %>
</p>

<p>
  <strong>Refund percent:</strong>
  <%= @packaging.refund_percent %>
</p>

<%= link_to 'Edit', edit_packaging_path(@packaging) %> |
<%= link_to 'Back', packagings_path %>